batch_size: 128
data_augmentation: {}
data_postprocessing: {}
data_preprocessing:
  test:
    resize:
    - 64
    - 64
  train:
    rescale: {"out_min_max": [-1,1]}
    resize:
    - 64
    - 64
  val:
    resize:
    - 64
    - 64
  inference:
    resize:
    - 64
    - 64
dataloader_config:
  inference:
    drop_last: false
    num_workers: 0
    pin_memory: false
    shuffle: false
  test:
    drop_last: false
    num_workers: 0
    pin_memory: false
    shuffle: false
  train:
    drop_last: false
    num_workers: 4
    pin_memory: True
    shuffle: true
    prefetch_factor: 8
  validation:
    drop_last: false
    num_workers: 0
    pin_memory: false
    shuffle: false
in_memory: false
inference_parameters:
  batch_size: 1
  n_images_to_generate: 10

modality: rad
model_config:
  amp: false
  architecture:
    latent_vector_size: 100
  converter_type: soft
  input_shape:
  - 64
  - 64
  labeling_paradigm: unlabeled
  losses:
    discriminator:
      name: BCELogits
    generator:
      name: BCELogits
  model_name: dcgan
  n_channels: 1
  n_dimensions: 2
  norm_type: batch
  optimizers:
    discriminator:
      betas:
      - 0.5
      - 0.999
      lr: 0.0002
      name: adam
    generator:
      betas:
      - 0.5
      - 0.999
      lr: 0.0002
      name: adam
  tensor_shape:
  - 64
  - 64
  save_eval_images_every_n_epochs: 5
  n_fixed_images_to_generate: 10
  fixed_images_batch_size: 10

num_epochs: 30
patience: 0
save_model_every_n_epochs: 5
verbose: true
version:
  maximum: 0.0.20-dev
  minimum: 0.0.14
