batch_size: 1
data_augmentation: {}
data_postprocessing: {}
data_preprocessing:
  test:
    resize:
    - 64
    - 64
  train:
    resize:
    - 64
    - 64
  val:
    resize:
    - 64
    - 64
  inference:
    resize:
    - 64
    - 64
dataloader_config:
  inference:
    drop_last: false
    num_workers: 0
    pin_memory: false
    shuffle: false
  test:
    drop_last: false
    num_workers: 0
    pin_memory: false
    shuffle: false
  train:
    drop_last: false
    num_workers: 0
    pin_memory: false
    shuffle: true
  validation:
    drop_last: false
    num_workers: 0
    pin_memory: false
    shuffle: false
# compute:
  # precision: "32"
  # num_devices: 2           # if not set, all GPUs available will be used
  # num_nodes: 2             # if not set, one node will be used
  # strategy: "ddp"        # it is one of ddp, deepspeed, fsdp. can be none, this way it will fallback to the default strategy (DDP if there are more than one GPU, if no gpus are available it will fallback to CPU)
  # strategy_config: {}    # it is a set of arguments for initialization of strategies. Look at https://lightning.ai/docs/pytorch/stable/api_references.html#strategies to see each of them. For deepspeed, it is only a path to the json config.

modality: rad
model_config:
  converter_type: soft
  labeling_paradigm: unlabeled
  losses:
    name: mse
  model_name: vqvae
  n_channels: 2
  n_dimensions: 2
  norm_type: batch
  optimizers:
      betas:
      - 0.5
      - 0.999
      lr: 0.0002
      name: adam
      weight_decay: 0.0
  schedulers:
    type: triangle
    step_size: 2
  tensor_shape:
  - 64
  - 64
inference_parameters:
  batch_size: 1
num_epochs: 1000
patience: 0
save_model_every_n_epochs: 1
verbose: true
version:
  maximum: 0.0.20-dev
  minimum: 0.0.14
