batch_size: 1
data_augmentation: {}
data_postprocessing: {}
data_preprocessing:
  test:
    resize:
    - 64
    - 64
  train:
    resize:
    - 64
    - 64
  val:
    resize:
    - 64
    - 64
  inference:
    resize:
    - 64
    - 64
dataloader_config:
  inference:
    drop_last: false
    num_workers: 0
    pin_memory: false
    shuffle: false
  test:
    drop_last: false
    num_workers: 0
    pin_memory: false
    shuffle: false
  train:
    drop_last: false
    num_workers: 0
    pin_memory: false
    shuffle: true
  validation:
    drop_last: false
    num_workers: 0
    pin_memory: false
    shuffle: false
in_memory: false
inference_parameters:
  batch_size: 1
  n_images_to_generate: 10

modality: rad
precision: "32"
model_config:
  architecture:
    latent_vector_size: 100
  converter_type: soft
  input_shape:
  - 64
  - 64
  labeling_paradigm: unlabeled
  losses:
    discriminator:
      name: BCELogits
    generator:
      name: BCELogits
  model_name: dcgan
  n_channels: 2
  n_dimensions: 2
  norm_type: batch
  schedulers:
    discriminator:
      type: triangle_modified
      step_size: 2
    generator:
      type: triangle_modified
      step_size: 2
  optimizers:
    discriminator:
      betas:
      - 0.5
      - 0.999
      lr: 0.0002
      name: adam
      weight_decay: 0.0
    generator:
      betas:
      - 0.5
      - 0.999
      lr: 0.0002
      name: adam
      weight_decay: 0.0
  tensor_shape:
    - 64
    - 64
  save_eval_images_every_n_epochs: 5
  n_fixed_images_to_generate: 10
  fixed_images_batch_size: 10

# compute:
#   precision: "32"
#   # num_devices: 2           # if not set, all GPUs available will be used
#   num_nodes: 2             # if not set, one node will be used
#   strategy: "ddp"        # it is one of ddp, deepspeed, fsdp. can be none, this way it will fallback to the default strategy (DDP if there are more than one GPU, if no gpus are available it will fallback to CPU)
#   strategy_config: {"find_unused_parameters" : True}
num_epochs: 1
patience: 0
save_model_every_n_epochs: 1
verbose: true
version:
  maximum: 0.0.20-dev
  minimum: 0.0.14
